version: "3.8"
services:
  workspace:
    image: mcr.microsoft.com/vscode/devcontainers/php:8.1
    volumes:
      - ..:/workspaces/${PWD##*/}
    ports:
      - "8080:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
